In [1]:
import numpy as np
import pandas as pd
import itertools
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
#The issue you're encountering is due to the fact that the sklearn package is deprecated. 
#Instead of pip install sklearn, you need to install scikit-learn directly. 
#!pip install sklearn

In [1]:
!pip install scikit-learn


In [ ]:
The error you're encountering, UnicodeDecodeError, typically occurs when the CSV file contains characters that aren't properly decoded using the default encoding (utf-8).

In [7]:
import pandas as pd

In [4]:
df=pd.read_csv('spam.csv', encoding='latin1') # #Latin-1 is occasionally, though imprecisely, referred to as Extended ASCII. This is because the first 128 characters of its set are identical to the US ASCII standard. 
df.shape                                             #The remainder of the set contains accented characters and symbols.


(5572, 5)

In [25]:
#Get shape and head
print(df.head(10))

     v1                                                                                                                                                                v2 Unnamed: 2 Unnamed: 3 Unnamed: 4
0   ham                                                   Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...        NaN        NaN        NaN
1   ham                                                                                                                                     Ok lar... Joking wif u oni...        NaN        NaN        NaN
2  spam       Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's        NaN        NaN        NaN
3   ham                                                                                                                 U dun say so early hor... U c already then say...        NaN        

In [5]:

pd.set_option('display.max_columns', None)  
pd.set_option('display.expand_frame_repr', False) #True (default): Splits/wraps the DataFrame across multiple lines if it's too wide.
                                                    #False: Displays the DataFrame in one continuous line, regardless of width.
pd.set_option('max_colwidth',None)  #Setting max_colwidth to None removes this limit. This means Pandas will display the full content of each cell, regardless of how long the text is.
df.head(10)

v1                                                                                                                                                                v2 Unnamed: 2 Unnamed: 3 Unnamed: 4
0   ham                                                   Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...        NaN        NaN        NaN
1   ham                                                                                                                                     Ok lar... Joking wif u oni...        NaN        NaN        NaN
2  spam       Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's        NaN        NaN        NaN
3   ham                                                                                                                 U dun say so early hor... U c already then say...        NaN        NaN        NaN
4   ham                                                                                                     Nah I don't think he goes to usf, he lives around here though        NaN        NaN        NaN
5  spam              FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv        NaN        NaN        NaN
6   ham                                                                                     Even my brother is not like to speak with me. They treat me like aids patent.        NaN        NaN        NaN
7   ham  As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune        NaN        NaN        NaN
8  spam    WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.        NaN        NaN        NaN
9  spam        Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030        NaN        NaN        NaN

In [27]:
df = df.rename(columns={'v1': 'category', 'v2': 'text'})
df


category                                                                                                                                                               text Unnamed: 2 Unnamed: 3 Unnamed: 4
0         ham                                                    Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...        NaN        NaN        NaN
1         ham                                                                                                                                      Ok lar... Joking wif u oni...        NaN        NaN        NaN
2        spam        Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's        NaN        NaN        NaN
3         ham                                                                                                                  U dun say so early hor... U c already then say...        NaN        NaN        NaN
4         ham                                                                                                      Nah I don't think he goes to usf, he lives around here though        NaN        NaN        NaN
...       ...                                                                                                                                                                ...        ...        ...        ...
5567     spam  This is the 2nd time we have tried 2 contact u. U have won the å£750 Pound prize. 2 claim is easy, call 087187272008 NOW1! Only 10p per minute. BT-national-rate.        NaN        NaN        NaN
5568      ham                                                                                                                              Will Ì_ b going to esplanade fr home?        NaN        NaN        NaN
5569      ham                                                                                                          Pity, * was in mood for that. So...any other suggestions?        NaN        NaN        NaN
5570      ham                                      The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free        NaN        NaN        NaN
5571      ham                                                                                                                                         Rofl. Its true to its name        NaN        NaN        NaN

[5572 rows x 5 columns]

In [28]:
newdf=df[['text', 'category']]
newdf

text category
0                                                       Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...      ham
1                                                                                                                                         Ok lar... Joking wif u oni...      ham
2           Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's     spam
3                                                                                                                     U dun say so early hor... U c already then say...      ham
4                                                                                                         Nah I don't think he goes to usf, he lives around here though      ham
...                                                                                                                                                                 ...      ...
5567  This is the 2nd time we have tried 2 contact u. U have won the å£750 Pound prize. 2 claim is easy, call 087187272008 NOW1! Only 10p per minute. BT-national-rate.     spam
5568                                                                                                                              Will Ì_ b going to esplanade fr home?      ham
5569                                                                                                          Pity, * was in mood for that. So...any other suggestions?      ham
5570                                      The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free      ham
5571                                                                                                                                         Rofl. Its true to its name      ham

[5572 rows x 2 columns]

In [3]:
CORPUS = [
'the sky is blue',
'sky is blue and sky is beautiful',
'the beautiful sky is so blue',
'i love blue cheese'
]
new_doc = ['loving this blue sky today']

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

# Define the corpus
CORPUS = [
    'the sky is blue',
    'sky is blue and sky is beautiful',
    'the beautiful sky is so blue',
    'i love blue cheese'
]

#new_doc = ['loving this blue sky today']

# Define a function to extract n-grams
def extract_ngrams(corpus, ngram_range=(1,1)):
    vectorizer = CountVectorizer(ngram_range=ngram_range)
    
    # Fit on corpus and transform both corpus and new document
    X_corpus = vectorizer.fit_transform(corpus)
    #X_new_doc = vectorizer.transform(new_doc)
    
    # Get feature names (n-grams)
    feature_names = vectorizer.get_feature_names_out()
    
    # Convert the results to arrays
    corpus_ngrams = X_corpus.toarray()
    #new_doc_ngrams = X_new_doc.toarray()
    
    return feature_names, corpus_ngrams

# Unigrams (1-gram)
unigrams, corpus_unigrams = extract_ngrams(CORPUS, ngram_range=(1, 1))
print("Unigrams:")
print(unigrams)
print(corpus_unigrams)
#print(new_doc_unigrams)



Unigrams:
['and' 'beautiful' 'blue' 'cheese' 'is' 'love' 'sky' 'so' 'the']
[[0 0 1 0 1 0 1 0 1]
 [1 1 1 0 2 0 2 0 0]
 [0 1 1 0 1 0 1 1 1]
 [0 0 1 1 0 1 0 0 0]]


In [ ]:
# Bigrams (2-grams)
bigrams, corpus_bigrams, new_doc_bigrams = extract_ngrams(CORPUS, new_doc, ngram_range=(2, 2))
print("\nBigrams:")
print(bigrams)
print(corpus_bigrams)
print(new_doc_bigrams)

# Trigrams (3-grams)
trigrams, corpus_trigrams, new_doc_trigrams = extract_ngrams(CORPUS, new_doc, ngram_range=(3, 3))
print("\nTrigrams:")
print(trigrams)
print(corpus_trigrams)
print(new_doc_trigrams)


TypeError: extract_ngrams() got multiple values for argument 'ngram_range'

In [14]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Define the corpus and new document
CORPUS = [
    'the sky is blue',
    'sky is blue and sky is beautiful',
    'the beautiful sky is so blue',
    'i love blue cheese'
]

new_doc = ['loving this blue sky today']

# Define a function to extract n-grams and return them as a DataFrame
def extract_ngrams_df(corpus, new_doc, ngram_range=(1,1)):
    vectorizer = CountVectorizer(ngram_range=ngram_range)
    
    # Fit on corpus and transform both corpus and new document
    X_corpus = vectorizer.fit_transform(corpus)
    print(type(X_corpus))
    print(X_corpus)
    X_new_doc = vectorizer.transform(new_doc)
    
    # Get feature names (n-grams)
    feature_names = vectorizer.get_feature_names_out()
    print("\n\n features names are: ",feature_names)

    features = X_corpus.toarray()           #toarray() and todense( ) are equivalent
    # Convert the results to arrays
    print("*********************************************************************")
    print("\n features are ",X_corpus.todense()) # dense matrix representation
    print("\n features are\n",features) # dense matrix representation
    print("\n\n")
    
    corpus_ngrams = X_corpus.toarray().sum(axis=0)  # Sum counts across all corpus documents
    #new_doc_ngrams = X_new_doc.toarray().flatten()  # Flatten the new document's array
    
    # Create a DataFrame for better visualization
    df1 = pd.DataFrame(data=features,
            columns=feature_names)
    
    df2 = pd.DataFrame({
        'N-gram': feature_names,
       'Corpus Count': corpus_ngrams,
        
     })

    
    
    return df1, df2

# Unigrams (1-gram)
df_unigrams1, df_unigrams2 = extract_ngrams_df(CORPUS, new_doc, ngram_range=(1, 1))
print("\n\nUnigrams1 DataFrame:")
print(df_unigrams1)
print("\n\nUnigrams2 DataFrame:")
print(df_unigrams2)

<class 'scipy.sparse._csr.csr_matrix'>
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 18 stored elements and shape (4, 9)>
  Coords	Values
  (0, 8)	1
  (0, 6)	1
  (0, 4)	1
  (0, 2)	1
  (1, 6)	2
  (1, 4)	2
  (1, 2)	1
  (1, 0)	1
  (1, 1)	1
  (2, 8)	1
  (2, 6)	1
  (2, 4)	1
  (2, 2)	1
  (2, 1)	1
  (2, 7)	1
  (3, 2)	1
  (3, 5)	1
  (3, 3)	1


 features names are:  ['and' 'beautiful' 'blue' 'cheese' 'is' 'love' 'sky' 'so' 'the']
*********************************************************************

 features are  [[0 0 1 0 1 0 1 0 1]
 [1 1 1 0 2 0 2 0 0]
 [0 1 1 0 1 0 1 1 1]
 [0 0 1 1 0 1 0 0 0]]

 features are
 [[0 0 1 0 1 0 1 0 1]
 [1 1 1 0 2 0 2 0 0]
 [0 1 1 0 1 0 1 1 1]
 [0 0 1 1 0 1 0 0 0]]





Unigrams1 DataFrame:
   and  beautiful  blue  cheese  is  love  sky  so  the
0    0          0     1       0   1     0    1   0    1
1    1          1     1       0   2     0    2   0    0
2    0          1     1       0   1     0    1   1    1
3    0          0     1       1   0    

In [ ]:
X_new_doc = vectorizer.transform(new_doc)
    
    # Get feature names (n-grams)
    feature_names = vectorizer.get_feature_names_out()
    print("\n\n features names are: ",feature_names)

    features = X_corpus.toarray()           #toarray() and todense( ) are equivalent
    # Convert the results to arrays
    #print("\n features are ",X_corpus.todense()) # dense matrix representation
    print("\n features are\n",features) # dense matrix representation
    print("\n\n")
    
    corpus_ngrams = X_corpus.toarray().sum(axis=0)  # Sum counts across all corpus documents
    #new_doc_ngrams = X_new_doc.toarray().flatten()  # Flatten the new document's array
    
    # Create a DataFrame for better visualization
    df1 = pd.DataFrame(data=features,
            columns=feature_names)
    
    df2 = pd.DataFrame({
        'N-gram': feature_names,
       'Corpus Count': corpus_ngrams,
        
     })

    
    
    return df1, df2





In [35]:
# Bigrams (2-grams)
df_bigrams1, df_bigrams2 = extract_ngrams_df(CORPUS, new_doc, ngram_range=(2, 2))
print("\nBigrams1 DataFrame:")
print(df_bigrams1)

print("\nBigrams2 DataFrame:")
print(df_bigrams2)




<class 'scipy.sparse._csr.csr_matrix'>
  (0, 11)	1
  (0, 8)	1
  (0, 5)	1
  (1, 8)	2
  (1, 5)	1
  (1, 2)	1
  (1, 0)	1
  (1, 4)	1
  (2, 8)	1
  (2, 10)	1
  (2, 1)	1
  (2, 6)	1
  (2, 9)	1
  (3, 7)	1
  (3, 3)	1


 features names are:  ['and sky' 'beautiful sky' 'blue and' 'blue cheese' 'is beautiful'
 'is blue' 'is so' 'love blue' 'sky is' 'so blue' 'the beautiful'
 'the sky']

 features are
 [[0 0 0 0 0 1 0 0 1 0 0 1]
 [1 0 1 0 1 1 0 0 2 0 0 0]
 [0 1 0 0 0 0 1 0 1 1 1 0]
 [0 0 0 1 0 0 0 1 0 0 0 0]]




Bigrams1 DataFrame:
   and sky  beautiful sky  blue and  blue cheese  is beautiful  is blue  is so  love blue  sky is  so blue  the beautiful  the sky
0        0              0         0            0             0        1      0          0       1        0              0        1
1        1              0         1            0             1        1      0          0       2        0              0        0
2        0              1         0            0             0        0      1     

In [ ]:
# Trigrams (3-grams)
df_trigrams = extract_ngrams_df(CORPUS, new_doc, ngram_range=(3, 3))
print("\nTrigrams DataFrame:")
print(df_trigrams)

In [13]:
arr=[
      [1, 1, 1, 1],  # Document 1
      [0, 2, 1, 1],  # Document 2
      [1, 1, 1, 1]   # Document 3
   ]


In [15]:
arr.torray().sum(axis=0) #will sum the counts for each unigram (column-wise) across all documents:

AttributeError: 'list' object has no attribute 'torray'

In [18]:
from scipy.sparse import csr_matrix
import numpy as np

# Define non-zero values and their coordinates
data = np.array([3, 4, 5])          # Non-zero values
row_indices = np.array([0, 1, 2])   # Row indices
col_indices = np.array([2, 0, 1])   # Column indices

# Create a sparse matrix
sparse_matrix = csr_matrix((data, (row_indices, col_indices)), shape=(3, 3))

# Display the sparse matrix
print(sparse_matrix)


  (0, 2)	3
  (1, 0)	4
  (2, 1)	5


In [19]:
from scipy.sparse import csr_matrix

# Define a dense 2D list (matrix)
dense_array = [
    [0, 0, 3],
    [4, 0, 0],
    [0, 5, 0]
]

# Create a sparse matrix
sparse_matrix = csr_matrix(dense_array)

# Display the sparse matrix
print(sparse_matrix)


  (0, 2)	3
  (1, 0)	4
  (2, 1)	5


In [20]:
sparse_matrix.toarray()

array([[0, 0, 3],
       [4, 0, 0],
       [0, 5, 0]], dtype=int32)

In [21]:
sparse_matrix.toarray().sum(axis=0)

array([4, 5, 3], dtype=int32)

In [12]:
df=pd.read_csv('spam.csv', encoding='latin1') # #Latin-1 is occasionally, though imprecisely, referred to as Extended ASCII. This is because the first 128 characters of its set are identical to the US ASCII standard. 
df.shape    

(5572, 5)

In [5]:
df = df.rename(columns={'v1': 'category', 'v2': 'text'})
newdf=df[['text', 'category']]
newdf

text category
0     Go until jurong point, crazy.. Available only ...      ham
1                         Ok lar... Joking wif u oni...      ham
2     Free entry in 2 a wkly comp to win FA Cup fina...     spam
3     U dun say so early hor... U c already then say...      ham
4     Nah I don't think he goes to usf, he lives aro...      ham
...                                                 ...      ...
5567  This is the 2nd time we have tried 2 contact u...     spam
5568              Will Ì_ b going to esplanade fr home?      ham
5569  Pity, * was in mood for that. So...any other s...      ham
5570  The guy did some bitching but I acted like i'd...      ham
5571                         Rofl. Its true to its name      ham

[5572 rows x 2 columns]

Step 2: Data Analysis<br>
1. Check for Missing Values: It’s essential to check if there are any missing values in your DataFrame.
2. Class Distribution: Check how many messages are "ham" and how many are "spam."

In [35]:
print(newdf['text'].isnull().sum(axis=0))

0


In [8]:
print(newdf.isnull().sum())


text        0
category    0
dtype: int64


In [36]:
#Class Distribution: Check how many messages are "ham" and how many are "spam."
print(df['category'].value_counts())


category
ham     4825
spam     747
Name: count, dtype: int64


1. Step 3: Text Preprocessing
2. Before you can use this data for modeling, you typically need to preprocess the text data. Common steps include:

3. Lowercasing
4. Removing punctuation
5. Removing stop words
6. Tokenization
7. Converting text to numerical features (e.g., using Bag of Words or TF-IDF)

In [41]:
s=r'\n'
print(s)
t= '\n'
print(t)

\n




In [53]:
text='&&&&&akhtar age is 14 and??? saeed age is 15 are %%%friends but they usually++++++++disagree on certain matters'
text1=re.sub(r'[^a-zA-Z0-9\s]', '', text)
text1=text1.split(" ")
text1

['akhtar',
 'age',
 'is',
 '14',
 'and',
 'saeed',
 'age',
 'is',
 '15',
 'are',
 'friends',
 'but',
 'they',
 'usuallydisagree',
 'on',
 'certain',
 'matters']

In [54]:
from nltk.corpus import stopwords

In [55]:
stop = stopwords.words('english')


In [56]:
cleantext=[x for x in text1 if x not in stop]
cleantext

['akhtar',
 'age',
 '14',
 'saeed',
 'age',
 '15',
 'friends',
 'usuallydisagree',
 'certain',
 'matters']

In [46]:
for i in stopwords:
    print(i)

TypeError: 'WordListCorpusReader' object is not iterable

In [67]:
text= ['akhtar',  'age',  'is',  '14',  'and','15']
print(" ".join(text))

akhtar age is 14 and 15


In [68]:
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

# Function to preprocess text
def preprocess_text(text):
    # Lowercase the text
    text = text.lower()
    # Remove punctuation and non-alphanumeric characters
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = text.split(" ")
    
    text = [x for x in text if x not in stop]
    return " ".join(text)

# Apply preprocessing to the Message column
df['Cleaned_Text'] = df['text'].apply(preprocess_text)

# Display the cleaned messages
print(df[['text', 'Cleaned_Text']].head(6))


                                                                                                                                                          text                                                                                                                             Cleaned_Text
0                                              Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...                                                       go jurong point crazy available bugis n great world la e buffet cine got amore wat
1                                                                                                                                Ok lar... Joking wif u oni...                                                                                                                  ok lar joking wif u oni
2  Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry questio

In [69]:
# Display the cleaned messages
print(df[['Cleaned_Text']].head(2))

                                                                         Cleaned_Text
0  go jurong point crazy available bugis n great world la e buffet cine got amore wat
1                                                             ok lar joking wif u oni


1. Step 4: Feature Extraction
2. You can use CountVectorizer to convert the cleaned text data into numerical format.

In [70]:
# Create features and labels
X = df['Cleaned_Text']
y = df['category']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)




In [71]:
# Vectorize the text data
vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train)


In [72]:
X_test_vectorized = vectorizer.transform(X_test)

print(X_train_vectorized.shape)
print(X_test_vectorized.shape)
print(X_train_vectorized[0].toarray())

(4457, 8218)
(1115, 8218)
[[0 0 0 ... 0 0 0]]


In [20]:
# Vectorize the text data with bigrams
vectorizer = CountVectorizer(ngram_range=(2, 2))  # Extract bigrams
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

print(X_train_vectorized.shape)
print(X_test_vectorized.shape)

# Vectorize the text data with trigrams
vectorizer = CountVectorizer(ngram_range=(3, 3))  # Extract trigrams
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

print(X_train_vectorized.shape)
print(X_test_vectorized.shape)



NameError: name 'X_train' is not defined

In [ ]:

# Vectorize the text data with unigrams, bigrams, and trigrams
vectorizer = CountVectorizer(ngram_range=(1, 3))  # Extract unigrams, bigrams, and trigrams
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

print(X_train_vectorized.shape)
print(X_test_vectorized.shape)

Step 5: Building a Classifier